[package]
name = "benches"
version = "0.1.0"
edition = "2021"


[dependencies]
criterion = "0.5"
fmmap = { path = "../fmmap-rs", features = ["sync", "tokio"] }
tokio = { version = "1", features = ["full"] }
